services:
  mongodb:
    image: mongo:8.0.4-noble
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always

volumes:
  mongodb_data:
    driver: local
